version: '3'
services:
  composeops:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ABC=123
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config.local.yml:/config.yml
    