auth:
  [name]: 
    username: string
    password: string
    keyPath: string
    keyPassword: string

services:
  - [name]:
      url: string
      ref: string
      auth: string 
      interval: number